### ISSUE TITLE
error salmon quant:  cannot recognize file extension

### ISSUE THREAD

**Issue by silulinlulu** [FemeniasM/ExplorATEproject#7]
Hello

I am using ExplorATE to quantify TE expression in my data and ecountered the following error:
Quantifying with Salmon
=======================ESC(BESC[m
ESC[31m[2023-10-13 11:58:53][ERROR] FileExtensionError: Invalid extensionESC(BESC[m
ESC[32mSupported extensions are: <.fq> or <.fastq> or <.fq.gz> or <.fastq.gz>ESC(BESC[m

i don't know why this occurs because the read files are all named as read1.fq.gz, which shold be the format that salmon can recognize.
to prove this, i ran salmon quant  seperately using the reference files generated by ExplorATE before the error, on the same read files and it worked fine. 

could you please shed a light on this issue? 

Thank you very much and i am looking forward to your reply.

Silu

**Comment by BravoScarleth** [comment]
Hi silu,

Maybe the response is too late for you to solve the problem. But it can be useful to others.
I had the same problem and I fixed it easily.
Literally, the names of the input PE sequence files must have _R1 and _R2. Example: sample_R1.fq and sample_R2.fq.
In your case it should be called read_R1.fq.gz and not read1.fq.gz.

Regards

**Comment by silulinlulu** [comment]
Hi

Thanks very much for the reply. I realized this was the problem after I posted the issue. Thanks anyways.

Regards
Silu
